-- V3: Create organization table
CREATE TABLE IF NOT EXISTS organization (
    id INT PRIMARY KEY AUTO_INCREMENT COMMENT '组织ID',
    name VARCHAR(100) NOT NULL COMMENT '组织名称',
    parent_id INT DEFAULT NULL COMMENT '父组织ID',
    level INT DEFAULT 1 COMMENT '组织层级',
    path VARCHAR(500) DEFAULT '/' COMMENT '组织路径',
    sort INT DEFAULT 0 COMMENT '排序',
    status TINYINT DEFAULT 1 COMMENT '1:启用 0:禁用',
    create_time DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    update_time DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='组织表';